assignments_table:
  cart0:
    x: -5
    y: -8.0
    theta: -1.57
  cart1:
    x: -4
    y: -8.0
    theta: -1.57
  cart2:
    x: -3
    y: -8.0
    theta: -1.57
  cart3:
    x: -2
    y: -8.0
    theta: -1.57
  cart4:
    x: -1
    y: -8.0
    theta: -1.57
  cart5:
    x: 0
    y: -8.0
    theta: -1.57
  cart6:
    x: 1
    y: -8.0
    theta: -1.57
  cart7:
    x: 2
    y: -8.0
    theta: -1.57
  cart8:
    x: 3
    y: -8.0
    theta: -1.57
  cart9:
    x: 4
    y: -8.0
    theta: -1.57
